schema_version: 1

context:
  python_min: "3.11"
  version: "2.6.0"

package:
  name: pydeflate
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pydeflate/pydeflate-${{ version }}.tar.gz
  sha256: 4d06209e33e15dc4fc31a892efd70ddb727a016ab4bbd0fba8dfc440e6b683e4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.8.22,<0.9
    - pip
  run:
    - python >=${{ python_min }}
    - imf-reader >=1.5.0
    - oda-reader >=1.4.2
    - pandas >=2.0
    - pandera >=0.20.0
    - pyarrow >=14.0
    - requests-cache >=1.2
    - requests >=2.33.0
    - wbgapi >=1.0.12
    - platformdirs >=3.0.0
    - filelock >=3.15.0

tests:
  - python:
      imports:
        - pydeflate
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Package to convert current prices figures to constant prices and vice versa
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/jm-rivera/pydeflate

extra:
  recipe-maintainers:
    - brynpickering
    - jm-rivera
